# up 명령어 : docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml up -d --build
# down 명령어 : docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml down
# log 명령어 : docker-compose --env-file .env.dev -f docker-compose.yml -f docker-compose.dev.yml logs -f

version: '3.8'

services:
  # --- Infra (Ports Open) ---
  server-data-db:
    ports:
      - "5432:5432"
    env_file: .env.dev

  redis:
    ports:
      - "6379:6379"

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file: .env.dev

  kafka:
    ports:
      - "29092:29092"
      - "9092:9092"

  kafka-ui:
    ports:
      - "7080:8080"

  # --- Apps (Dev Profile & Env) ---
  eureka:
    ports:
      - "19090:19090"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  gateway:
    ports:
      - "19091:19091"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  cdn:
    ports:
      - "19096:19096"
    volumes:
      # .env.dev의 CDN_LOCAL_PATH 사용
      - ${CDN_LOCAL_PATH}:/app/cdn/images
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  url:
    ports:
      - "19093:19093"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  data:
    ports:
      - "19095:19095"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  upload:
    ports:
      - "19092:19092"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  convert:
    ports:
      - "19097:19097"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  resize:
    ports:
      - "19098:19098"
    env_file: .env.dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  zipkin:
    ports:
      - "9411:9411"

  prometheus:
    ports:
      - "9090:9090"
    volumes:
      # 앞서 만든 dev용 설정 파일을 컨테이너 내부에 마운트합니다.
      - ./monitoring/prometheus/prometheus.dev.yml:/etc/prometheus/prometheus.yml

  grafana:
    ports:
      - "3000:3000"
    # Dev 환경은 컨테이너가 내려가면 대시보드 데이터가 날아가도 상관없으므로 볼륨 생략 가능

  loki:
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml

  promtail:
    volumes:
      - ./monitoring/promtail/promtail-config.yml:/etc/promtail/config.yml
      # 호스트(내 PC)의 도커 컨테이너 로그가 쌓이는 경로를 읽기 전용(ro)으로 마운트
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
