version: '3.8'

services:
  # --- Infrastructure Services ---
  server-data-db:
    container_name: server_data_db
    image: postgres:15
    volumes:
      - server_data_db:/var/lib/postgresql/data
    networks:
      - image_network

  redis:
    image: redis:latest
    container_name: image_redis
    networks:
      - image_network

  zipkin:
    image: openzipkin/zipkin
    container_name: image_zipkin
    networks:
      - image_network

  zookeeper:
    image: wurstmeister/zookeeper:latest
    platform: linux/amd64
    networks:
      - image_network

  kafka:
    image: wurstmeister/kafka:latest
    platform: linux/amd64
    networks:
      - image_network
    depends_on:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  minio:
    image: minio/minio
    container_name: minio
    networks:
      - image_network

  # --- Application Services (Skeleton) ---
  eureka:
    networks:
      - image_network

  gateway:
    networks:
      - image_network
    depends_on:
      - eureka

  upload:
    networks:
      - image_network
    depends_on:
      - eureka
      - kafka

  cdn:
    networks:
      - image_network
    depends_on:
      - eureka
      - redis

  url:
    networks:
      - image_network
    depends_on:
      - eureka

  data:
    networks:
      - image_network
    depends_on:
      - eureka
      - server-data-db

  convert:
    networks:
      - image_network
    depends_on:
      - eureka
      - kafka

  resize:
    networks:
      - image_network
    depends_on:
      - eureka
      - kafka

networks:
  image_network:
    driver: bridge

volumes:
  server_data_db:
