spring:
  application:
    name: gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: upload
          uri: lb://upload
          predicates:
            - Path=/image/upload/**
        - id: cdn
          uri: lb://cdn
          predicates:
            - Path=/cdn/**
        - id: fetch
          uri: lb://fetch
          predicates:
            - Path=/fetch/**
server:
  port: 19091
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
