spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

cdn:
  image:
    path: ${CDN_LOCAL_PATH}
    url: ${CDN_EXTERNAL_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
    register-with-eureka: true
    fetch-registry: true
