spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}

minio:
  url: ${MINIO_ENDPOINT}
  access:
    key: ${MINIO_ACCESS_KEY}
    secret: ${MINIO_SECRET_KEY}
  buckets:
    downloadBucket: ${MINIO_BUCKET_DOWNLOAD}
    uploadBucket: ${MINIO_BUCKET_UPLOAD}

cdn-server:
  url: ${CDN_EXTERNAL_URL}

logging:
  level:
    org.hibernate.orm.jdbc.bind: ${LOG_LEVEL_DB}
